# Generated by Django 5.0.6 on 2024-07-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclassroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='myclassroom.perfildocente'),
            preserve_default=False,
        ),
    ]
